export class BTS {
  edit?: boolean;
  id: number|any;
  hasElectricityStr?: string;
  siteOnNims?: string;
  stationCode: string;
  latitude?: string ;
  longitude?: string ;
  contractNo?: string;
  contractNoUpate?: string;
  address?: string;
  addressUpdate?: string;
  name?: string;
  nameUpdate?: string;
  provinceName?: string;
  provinceCode?: string;
  provinceCodeStr?: string;
  districtName?: string ;
  districtStr?: string ;
  telephone?: string;
  startDatePayment?: string;
  startDatePaymentUpdate?: string;
  endDatePayment?: string;
  endDatePaymentUpdate?: string;
  rentalFee?: string; // đơn giá thuê
  paymentTime?: number;
  fileContract?: string;
  hasElectricity?: number;
  hasElectricityValue?: number;
  periodOfRent?: number;
  startDateContract?: string;
  endDateContract?: string;
  rentalPrice?: string; // Phí thuê
  approvedStatus?: string;
  status?: number[];
  approvedStatusName?: string;
  approvedStatusStr?: string;
  statusName?: string;
  notes?: string;
  turnOffDate?: string;
  fileCR?: string;
  signDateContract?: string;
  signDateContractTypeDate?: string;
  categories?: string;
  isChecked?: boolean;
  province?: any;
  district?: any;
  listDistrictToUpdate?: any[];
  amount: string;
  endDateTypeDate?: string;
  startDateTypeDate?: string;
  startDateContractTypeDate?: string;
  endDateContractTypeDate?: string;
  siteOnContract?: string;
  createdUser?: string;
  createdDate?: string;
  btsAiredDate?: string;
  lastModifiedUser?: string;
  lastModifiedDate?: string;
  fileContractName?: string;
  fileCRName?: string;
  fileCRPath?: string;
  fileContractPath?: string;
  fileContractEdited?: boolean;
  fileContractNameTemp?: string;
  fileContractPathTemp?: string;
  fileCREdited?: boolean;
  fileCRNameTemp?: string;
  fileCRPathTemp?: string;
}
