export const cm = {
  no: 'STT',
  search: "Tìm kiếm",
  resset: "Nhập lại",
  searchInfor: "Thông tin tìm kiếm",
  list: "Danh sách",
  systemConfig: "Quản lý hệ thống",
  optionSet: "Quản lý cấu hình",
  optionSetValue: 'Quản lý tham số cấu hình',
  optionSetCode: "Mã cấu hình",
  searchAdvance: "Tìm kiếm nâng cao",
  add: "Thêm mới",
  edit: "Cập nhật",
  delete: "Xóa",
  createBy: "Người tạo",
  createDatetime: "Ngày tạo",
  confirmDelete: "Xác nhận xóa",
  confirmAdd: "Xác nhận thêm mới",
  confirmEdit: "Xác nhận cập nhật",
  editSuccess: "Cập nhật thành công",
  addSuccess: "Thêm mới thành công",
  delSuccess: "Xóa thành công",
  close: "Đóng",
  save: "Lưu",
  error: "Lỗi",
  success: "Thành công",
  warning: "Cảnh báo",
  info: "Thông tin",
  description: "Mô tả",
  action: "Hành động",
  language: "Ngôn ngữ",
  // option-set-value...
  value: 'Mã tham số cấu hình',
  // ...option-set-value
  nameVi: 'Tên(Vi)',
  nameEn: 'Tên(En)',
  nameLa: 'Tên(La)',
  of: 'của'
};
