export const cm = {
  search: "Tìm kiếm",
  resset: "Nhập lại",
  searchInfor: "Thông tin tìm kiếm",
  list: "Danh sách",
  systemConfig: "Quản lý hệ thống",
  optionSet: "Quản lý cấu hình",
  optionSetCode: "Mã cấu hình",
  searchAdvance: "Tìm kiếm nâng cao",
  add: "Thêm mới",
  edit:"Cập nhật",
  createBy: "Người tạo",
  createDatetime: "Ngày tạo",
  confirmDelete:"Xác nhận xóa",
};
