/**
 * BCCS3 APIS
 * No description provided (generated by Swagger Codegen https?://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version?: 1.0.1
 *
 *
 * NOTE?: This class is auto generated by the swagger code generator program.
 * https?://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 */
export interface CommonDialogModel {
  type?: 'ERROR' | 'SUCCESS' | 'WARNING' | 'INFO',
  title?: string,
  message?: string,
  retry?: boolean,
  hideCancelBtn?: boolean,
  cancel?: boolean,
  close?: boolean,
  continue?: boolean,
  stay?: boolean,
  delete?: boolean,
  yes?: boolean,
    no?: boolean,
    agree?: boolean,
    cancel_ta?: boolean,
  btn?: any[],
  // TechAsians thêm trường hợp: với việc sử dụng các modal này vào việc confirm thành công => ấn button X (đóng modal) với data giống như close có data
  hasCancelLikeClose?: boolean;
  hasCancelLikeCloseStr?: string;
  enableConfirmInputText?: boolean;
  requiredConfirmInputText?: boolean;
  requiredErrorMessage?: string;
  confirmInputTextPlaceHolder?: string;
}
